### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by bouhartsev** [bouhartsev/amonic_airlines#10]
Backend side:

- [ ] Routing for complex trips
- [ ] Deploy to Netlify (+ssl)

Client side (must have):

- [ ] Booking page (first, third parts, make it work)
- [ ] Profile page (form on login with last error description)
- [ ] Users page (fix user adding error)
- [ ] Schedules (dates, uploading and etc.)
- [ ] Surveys (layout and data loading)
- [ ] Tickets
- [ ] Network error boundary (!) - for security too

Client side (additional features):

- [ ] Main page
- [ ] PWA
- [ ] Fancy loader (with logo)
- [ ] README and .env.example
